export const NewArrivalsData = [
  {
    id: 9,
    title: 'Glass Wave Decor',
    description: 'Elegant glass decoration shaped like waves.',
    price: 50,
    imageUrl: '/new-arrivals/item8.png',
  },
  {
    id: 10,
    title: 'Elegance Dinnerware Set',
    description: 'Porcelain white dinnerware.',
    price: 75,
    imageUrl: '/new-arrivals/item9.png',
  },
  {
    id: 11,
    title: 'Blue & White Pillows',
    description: 'Soft, cotton pillows in coastal colors.',
    price: 40,
    imageUrl: '/new-arrivals/item10.png',
  },
  {
    id: 12,
    title: 'Oceanic Wall Art',
    description: 'Vibrant painting inspired by the sea.',
    price: 30,
    imageUrl: '/new-arrivals/item11.png',
  },
  {
    id: 13,
    title: 'Whale Plates',
    description: 'Playful ceramic whale-shaped plates.',
    price: 55,
    imageUrl: '/new-arrivals/item12.png',
  },
  {
    id: 14,
    title: 'Pendulum Art',
    description: 'A unique painting on canvas.',
    price: 95,
    imageUrl: '/new-arrivals/item13.png',
  },
  {
    id: 15,
    title: 'Ocean Wave Lamp',
    description: 'Curved, metal sea-inspired lamp.',
    price: 65,
    imageUrl: '/new-arrivals/item14.png',
  },
  {
    id: 16,
    title: 'White Sands Stool',
    description: 'Minimalist white stool, perfect for any space.',
    price: 75,
    imageUrl: '/new-arrivals/item15.png',
  },
];
