export const NewArrivalsData = [
  {
    id: 9,
    name: 'Glass Wave Decor',
    short_short_description: 'Elegant glass decoration shaped like waves.',
    price: 50,
    main_image_url: '/new-arrivals/item8.png',
  },
  {
    id: 10,
    name: 'Elegance Dinnerware Set',
    short_description: 'Porcelain white dinnerware.',
    price: 75,
    main_image_url: '/new-arrivals/item9.png',
  },
  {
    id: 11,
    name: 'Blue & White Pillows',
    short_description: 'Soft, cotton pillows in coastal colors.',
    price: 40,
    main_image_url: '/new-arrivals/item10.png',
  },
  {
    id: 12,
    name: 'Oceanic Wall Art',
    short_description: 'Vibrant painting inspired by the sea.',
    price: 30,
    main_image_url: '/new-arrivals/item11.png',
  },
  {
    id: 13,
    name: 'Whale Plates',
    short_description: 'Playful ceramic whale-shaped plates.',
    price: 55,
    main_image_url: '/new-arrivals/item12.png',
  },
  {
    id: 14,
    name: 'Pendulum Art',
    short_description: 'A unique painting on canvas.',
    price: 95,
    main_image_url: '/new-arrivals/item13.png',
  },
  {
    id: 15,
    name: 'Ocean Wave Lamp',
    short_description: 'Curved, metal sea-inspired lamp.',
    price: 65,
    main_image_url: '/new-arrivals/item14.png',
  },
  {
    id: 16,
    name: 'White Sands Stool',
    short_description: 'Minimalist white stool, perfect for any space.',
    price: 75,
    main_image_url: '/new-arrivals/item15.png',
  },
];
