export const SalesData = [
  {
    id: 16,
    name: 'Hanging Planter',
    short_description: 'Elegant ceramic and rope plant hanger.',
    price: 65,
    discounted_price: 40,
    main_image_url: '/sales/item16.png',
  },
  {
    id: 17,
    name: 'Fish-Shaped Plates',
    short_description: 'Whimsical fish-shaped ceramic plates.',
    price: 80,
    discounted_price: 35,
    main_image_url: '/sales/item17.png',
  },
  {
    id: 18,
    name: 'Nautical Plates',
    short_description: 'Porcelain nautically themed plates.',
    price: 75,
    discounted_price: 50,
    main_image_url: '/sales/item18.png',
  },
  {
    id: 19,
    name: 'Driftwood Shelf',
    short_description: 'Unique wooden geometric shelf.',
    price: 65,
    discounted_price: 55,
    main_image_url: '/sales/item19.png',
  },
  {
    id: 20,
    name: 'Outdoor Furniture Set',
    short_description: 'Weather-resistant wicker and wood.',
    price: 650,
    discounted_price: 450,
    main_image_url: '/sales/item20.png',
  },
  {
    id: 21,
    name: "Mariner's Lamp",
    short_description: 'Metal and wood maritime-inspired desk lamp.',
    price: 80,
    discounted_price: 60,
    main_image_url: '/sales/item21.png',
  },
  {
    id: 22,
    name: 'Coral Reef Vases',
    short_description: 'Delicate ceramic coral vases.',
    price: 65,
    discounted_price: 45,
    main_image_url: '/sales/item22.png',
  },
  {
    id: 23,
    name: 'Coastal Reflection Mirror',
    short_description: 'A sleek round mirror with a marine vibe.',
    price: 95,
    discounted_price: 65,
    main_image_url: '/sales/item23.png',
  },
];
