export const SalesData = [
  {
    id: 16,
    title: 'Hanging Planter',
    description: 'Elegant ceramic and rope plant hanger.',
    oldPrice: '65 €',
    price: '40 €',
    imageUrl: '/sales/item16.png',
  },
  {
    id: 17,
    title: 'Fish-Shaped Plates',
    description: 'Whimsical fish-shaped ceramic plates.',
    oldPrice: '80 €',
    price: '35 €',
    imageUrl: '/sales/item17.png',
  },
  {
    id: 18,
    title: 'Nautical Plates',
    description: 'Porcelain nautically themed plates.',
    oldPrice: '75 €',
    price: '50 €',
    imageUrl: '/sales/item18.png',
  },
  {
    id: 19,
    title: 'Driftwood Shelf',
    description: 'Unique wooden geometric shelf.',
    oldPrice: '65 €',
    price: '55 €',
    imageUrl: '/sales/item19.png',
  },
  {
    id: 20,
    title: 'Outdoor Furniture Set',
    description: 'Weather-resistant wicker and wood.',
    oldPrice: '650 €',
    price: '450 €',
    imageUrl: '/sales/item20.png',
  },
  {
    id: 21,
    title: "Mariner's Lamp",
    description: 'Metal and wood maritime-inspired desk lamp.',
    oldPrice: '80 €',
    price: '60 €',
    imageUrl: '/sales/item21.png',
  },
  {
    id: 22,
    title: 'Coral Reef Vases',
    description: 'Delicate ceramic coral vases.',
    oldPrice: '65 €',
    price: '45 €',
    imageUrl: '/sales/item22.png',
  },
  {
    id: 23,
    title: 'Coastal Reflection Mirror',
    description: 'A sleek round mirror with a marine vibe.',
    oldPrice: '95 €',
    price: '95 €',
    imageUrl: '/sales/item22.png',
  },
];
